### ISSUE TITLE
missing several ip-sysctl entries in BreadandButter-15.4 for Stock 5.0.2

### ISSUE THREAD

**Issue by braveheartleo** [TheNotOnly/android_kernel_lge_jagnm_lp#2]
Hi,

I wish to report that several ip-sysctl entries are missing in `BreadandButterKernel#15.4-D724` that I flashed in my stock Android 5.0.2 for my D724 device.

Of particular interest to me is `/proc/sys/net/ipv4/tcp_congestion_control` control knob, apart from other `tcp_*` variables that are missing as well. Because of this, I could not select nor experiment with the various TCP congestion control algorithms. Perhaps a kernel config might have been missed?

**Comment by nicksspirit** [comment]
Would you like to make a pull request to fix it. At the moment  I am quite
preoccupied with school. I won't be able to fix things anytime yet.

**Comment by braveheartleo** [comment]
> Would you like to make a pull request to fix it. At the moment I am quite preoccupied with school. I won't be able to fix things anytime yet.

I can do that, but first I need to setup a build environment for this to test my fixes. I have done cross-compiles for embedded devices before in OpenWRT. I just need to read up on some documentation on how to do this with compiling kernels for Android.

It seems that I have to manually setup the cross-compiler for generating ARM binaries, which is quite different in OpenWRT. Do you have any links on how I go about compiling ARM kernel binaries that could point me in the right direction?

**Comment by nicksspirit** [comment]
As for cross compilers, we use Archtoolchain. But I'll look into things and
get back to you.
